### PR TITLE
move paraview_hello_world notebook from examples to HOWTOs; add cell triggering paraview installation on Colab

### PR DESCRIPTION
**Pull request by AgnieszkaZaba**
Addresses [#1467](https://github.com/open-atmos/PySDM/issues/1467)

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you @AgnieszkaZaba!

Let me suggest to:
- [ ] move this .ipynb file to the _HOWTOS folder (it does not reproduce results from the paper, Paraview was not used in the paper, while it does serve the purpose of explaining how to use Paraview to visualise results from 2D prescribed-flow simulations)
- [ ] annotate the `ln -s ...` workaround explaining that it aims to solve a problem with the Ubuntu package (especially that after Ubuntu upgrades on Colab, the problem will likely cease to exist, and the `ln -s ...` line will trigger an error, while the Paraview installation ill be fine)

**Comment by AgnieszkaZaba** [comment]
Thanks @slayoo! 
Definitely it belongs to howtos. I will move it.
Don't know yet what to do with the second point.

And I'll will look up ipyparaview

**Comment by slayoo** [comment]
> Don't know yet what to do with the second point.

We could:
- [ ] add a comment with links to https://discourse.paraview.org/t/paraview-error-while-loading-shared-libraries-libpdal-base-so-13-cannot-open-shared-object-file/14000 and https://discourse.paraview.org/t/paraview-error-while-loading-shared-libraries-libpdal-base-so-13-cannot-open-shared-object-file/14000
- [ ] do linking only in case the target path does not exist (this will also make this cell re-runnable on Colab):
- [ ] remove `sudo` - it shouldn't be needed on Colab (?)

```bash
! if [ ! -f /usr/lib/libpdal_base.so.13 ]; then ln -s /usr/lib/libpdal_base.so.15 /usr/lib/libpdal_base.so.13; fi
``` 
 
> And I'll will look up ipyparaview

Thanks! (but let's do it independently of this PR)

**Comment by AgnieszkaZaba** [comment]
>     * [ ]  add a comment with links to https://discourse.paraview.org/t/paraview-error-while-loading-shared-libraries-libpdal-base-so-13-cannot-open-shared-object-file/14000 and https://discourse.paraview.org/t/paraview-error-while-loading-shared-libraries-libpdal-base-so-13-cannot-open-shared-object-file/14000

I will add this [link](https://github.com/qgis/QGIS/issued/52433) as a second one.

**Comment by slayoo** [comment]
there is a typo, here's the url: https://github.com/qgis/QGIS/issues/52433#issuecomment-1792285094

**Comment by AgnieszkaZaba** [comment]
Thanks for noticing! 
Do you know why the second line with ldconfig getting me warnings? And it looks like it is not needed.

**Review by slayoo — APPROVED** [review]

**Comment by slayoo** [comment]
Thank you!

**Pull request merged**
