### PR TITLE
Add readme diagrams

### PR DESCRIPTION
**Pull request by edejong-caltech**

### CODE REVIEW

**Comment by slayoo** [comment]
@edejong-caltech, these diagrams are super attractive and it's a great idea to cater to newcomers (and help all developers alike) with such graphical summaries. Still, I feel, we first need to sort out the meaning of arrows on the diagrams (perhaps adding a legend) before merging.

As of now, the arrows seem to have very diverse meaning, e.g.:
- solid from Initialisation to Attributes means "user uses Initialisation to prepare initial values of attributes" (but these are passed to Builder)
- solid from Builder to Particulator means "a method of Builder is used to instantiate a Particulator"
- solid from Products to Particulator means "instances of products are passed (to Builder) to create a Particulator"
- solid from Exporters to SDM Simulation means "an instance of Simulation's particulator is passed to exporter's methods"
- solid from Particulator to SDM Simulation means "a simulation is controlled by calling Particulator's instance methods"
- what does it mean that from Formulae to Builder we have both dashed and solid lines? (Formulae is not used in builder.py at all, merely passed to attributes' ctors)
- dashed from physics to backends means "backend code uses physics code"? (but it always does so through Formulae...), 
- on the second diagram, all lines are solid but the connections are different than on the first on (e.g., physics connects to Dynamics and Initialisation)

I'd first decide how to depict "a call", "passing as argument", "instantation", "user-code reference", "explicit import in the code", ... 

@aulenok, @trontrytel, do you know of any example diagrams (or diagram standards/templates) that could help us convey consistently what do we mean by arrows on the diagram?

BTW, this PR now removes the `devops_tests` submodule entirely, hence the conflict.

Thanks!

**Comment by slayoo** [comment]
@edejong-caltech @trontrytel @abulenok 
I've just made an attempt to make Emily's README diagram resemble closer to what is happening in the code, and came up with the following busy graph:
```mermaid
 graph
    COAL[":Coalescence"] --->|passed as argument to| BUILDER_ADD_DYN(["Builder.add_dynamic()"])
    BUILDER_INSTANCE["builder :Builder"] -...-|has a method| BUILDER_BUILD(["Builder.build()"])
    ATTRIBUTES[attributes: dict] -->|passed as argument to| BUILDER_BUILD
    N_SD["n_sd :int"] -->|passed as argument to| BUILDER_INIT
    BUILDER_INSTANCE -..-|has a method| BUILDER_SET_ENV(["Builder.set_environment()"])
    BUILDER_INIT(["Builder.__init__()"]) ----->|instantiates| BUILDER_INSTANCE
    BUILDER_INSTANCE -..-|has a method| BUILDER_ADD_DYN(["Builder.add_dynamic()"])
    ENV_INIT(["Box.__init__()"]) --->|instantiates| ENV
    DT[dt :float] ----->|passed as argument to| ENV_INIT
    DV[dv :float] ----->|passed as argument to| ENV_INIT
    ENV[":Box"] -->|passed as argument to| BUILDER_SET_ENV
    B["b: float"] --->|passed as argument to| KERNEL_INIT(["Golovin.__init__()"])
    KERNEL_INIT -->|instantiates| KERNEL
    KERNEL[collision_kernel: Golovin] -->|passed as argument to| COAL_INIT(["Coalesncence.__init__()"])
    COAL_INIT -->|instantiates| COAL
    PRODUCTS[products: list] ----->|passed as argument to| BUILDER_BUILD
    NORM_FACTOR[norm_factor: float]-->|passed as argument to| EXP_INIT
    SCALE[scale: float]-->|passed as argument to| EXP_INIT
    EXP_INIT(["Exponential.__init__()"]) -->|instantiates| IS
    IS["initial_spectrum :Exponential"] -->|passed as argument to| CM_INIT
    CM_INIT(["ConstantMultiplicity.__init__()"]) -->|instantiates| CM_INSTANCE
    CM_INSTANCE[":ConstantMultiplicity"] -.-|has a method| SAMPLE
    SAMPLE(["ConstantMultiplicity.sample()"]) -->|returns| n
    SAMPLE -->|returns| volume
    n -->|added as element of| ATTRIBUTES
    PARTICULATOR_INSTANCE -.-|has a method| PARTICULATOR_RUN(["Particulator.run()"])
    volume -->|added as element of| ATTRIBUTES
    BUILDER_BUILD -->|returns| PARTICULATOR_INSTANCE["particulator :Particulator"]
    PARTICULATOR_INSTANCE -.-|has a field| PARTICULATOR_PROD(["Particulator.products:dict"])
    BACKEND_INSTANCE["backend :CPU"] -->|passed as argument to| BUILDER_INIT
    PRODUCTS -.-|accessible via| PARTICULATOR_PROD
    NP_LOGSPACE(["np.logspace()"]) -->|returns| EDGES 
    EDGES[radius_bins_edges: np.ndarray] -->|passed as argument to| SPECTRUM_INIT
    SPECTRUM_INIT["ParticleVolumeVersusRadiusLogarithmSpectrum.__init__()"] -->|instantiates| SPECTRUM
    SPECTRUM[":ParticleVolumeVersusRadiusLogarithmSpectrum"] -->|added as element of| PRODUCTS
```
It's not simpler, but it leaves less ambiguity as to how to interpret elements of the diagram wrt code.
Feedback welcome! Thank you @edejong-caltech for this initiative!

**Comment by edejong-caltech** [comment]
@slayoo I like the diagram you created! It is indeed complex, but I think it is a much more complete picture of what goes on in the code for someone trying to write a script. I think if we keep the general module layout as it is and then use your version for the README, that will be a good combination.

**Comment by slayoo** [comment]
Just added links to the above diagram.

This PR erroneously removes the entire `devops_tests` submodule, I will create a new one with the updated diagram and also will try to update the general module layout one. Stay tuned.

**Comment by edejong-caltech** [comment]
Thank you @slayoo ! Appreciate the help.

**Comment by slayoo** [comment]
superceded by https://github.com/open-atmos/PySDM/pull/1107

**Pull request closed without merging**
