### PR TITLE
add ventilation coefficient (Pruppacher & Rasmussen 1979 & Froessling 1938) + Reynolds number attr + air dynamic viscosity formulae + unit tests (incl. drop size changes upon ventilation-in-parcel-below-cloud vs. no-ventilation) + refactor of env vars __getitem__ logic

### PR DESCRIPTION
**Pull request by kaitlyn-loftus**
First attempt to add ventilation coefficient from [Pruppacher & Rasmussen (1979))](https://doi.org/10.1175/1520-0469(1979)036<1255:AWTIOT>2.0.CO;2).

Added methods for air dynamic viscosity, particle Reynolds number, and air Schmidt number to support ventilation coefficient calculation. 

Tried to add basic tests for dynamic viscosity and ventilation coefficient calculation but don't think I activated them...

### CODE REVIEW

**Comment by slayoo** [comment]
@kaitlyn-loftus, thanks!!!

For all PRs, we run the CI workflow in several steps, on of the first featuring `pylint` check (https://pylint.readthedocs.io/). Here it complains a bit:
```
************* Module PySDM.physics.ventilation.pruppacher_rasmussen_1979
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:2:0: C0301: Line too long (110/100) (line-too-long)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:3:0: C0301: Line too long (107/100) (line-too-long)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:5:0: C0301: Line too long (182/100) (line-too-long)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:69:0: C0301: Line too long (131/100) (line-too-long)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:83:0: C0301: Line too long (122/100) (line-too-long)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:17:4: C2401: Function name "calcηairEarth" contains a non-ASCII character, consider renaming it. (non-ascii-name)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:37:42: C2401: Argument name "ηair" contains a non-ASCII character, consider renaming it. (non-ascii-name)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:37:49: C2401: Argument name "ρair" contains a non-ASCII character, consider renaming it. (non-ascii-name)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:53:15: C2401: Argument name "ηair" contains a non-ASCII character, consider renaming it. (non-ascii-name)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:53:25: C2401: Argument name "ρair" contains a non-ASCII character, consider renaming it. (non-ascii-name)
PySDM/physics/ventilation/pruppacher_rasmussen_1979.py:121:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
************* Module tests.smoke_tests.no_env.pruppacher_rasmussen_1979.test_dynvisvT
tests/smoke_tests/no_env/pruppacher_rasmussen_1979/test_dynvisvT.py:28:0: C2401: Function name "test_ηvT_figA5" contains a non-ASCII character, consider renaming it. (non-ascii-name)
tests/smoke_tests/no_env/pruppacher_rasmussen_1979/test_dynvisvT.py:28:23: C2401: Argument name "η" contains a non-ASCII character, consider renaming it. (non-ascii-name)
tests/smoke_tests/no_env/pruppacher_rasmussen_1979/test_dynvisvT.py:30:4: C2401: Variable name "η_test" contains a non-ASCII character, consider renaming it. (non-ascii-name)
```
For this reason, most of the tests were not run.
To check how to execute pylint locally, see: https://github.com/open-atmos/python-dev-hints/wiki/Pylint-FAQ

The `smoke_tests` folder is meant for tests that cannot be called "unit tests" for they involve executing multiple units of code. Here, I'd say you've implemented exactly what unit test should look like, so I'd suggest moving the new tests into `PySDM/tests/unit_tests/physics`. Any `'.py` file the begins with `test_` will be included in the test run, there is no need to activate it.

To run the unit tests locally, executing `pytest tests/unit_tests` should be enough.

Thanks again!

**Comment by slayoo** [comment]
Thank you!
The new test was executed and passed! (part of the`nojit_and_codecov` job which runs with Numba JIT turned off):
https://github.com/open-atmos/PySDM/actions/runs/7966038711/job/21746648231?pr=1282#step:4:808

**Comment by kaitlyn-loftus** [comment]
Great!! Thanks for explaining. I originally ran the pylint tests before staging the new files, so none of them got checked 😅

**Comment by slayoo** [comment]
@kaitlyn-loftus, in the above commit https://github.com/open-atmos/PySDM/pull/1282/commits/9c2269f8c2e895fcc7f9b95db8185a7dd007ac88, there are some refactors towards making the ventilation coefficient being used inside condensation/evaporation solver. Added also more unit tests and a simpler "classic" formula from Froessling 1938 for reference. Please have a look if the changes look OK? Next step on my side: use the ventilation coefficient in the condensation solver - stay tuned, thanks

**Comment by kaitlyn-loftus** [comment]
@slayoo these changes look good. Thanks for fixing the air density to include the water vapor contribution; I had meant to flag that as a todo. The only potential issue I see is how the ventilation_coefficient method in PySDM/physics/ventilation/pruppacher_rasmussen_1979.py would handle sqrt_re_times_cbrt_sc=const.PRUPPACHER_RASMUSSEN_1979_XTHRES. This looks to me like it would give NaN.

**Comment by slayoo** [comment]
> The only potential issue I see is how the ventilation_coefficient method in PySDM/physics/ventilation/pruppacher_rasmussen_1979.py would handle sqrt_re_times_cbrt_sc=const.PRUPPACHER_RASMUSSEN_1979_XTHRES. This looks to me like it would give NaN (unless there is some clever handling elsewhere in the code).

Very valid point! Thanks, @kaitlyn-loftus 
Here's a fix with a new test added checking behavior at the threshold value: https://github.com/open-atmos/PySDM/pull/1282/commits/4917da426aed044a5b3cdc8aa26f2c8f2d3c2f95

**Comment by kaitlyn-loftus** [comment]
I think this will still give 0 at the threshold, instead of ~1.02. Is np.heaviside friendly with the CPU and GPU accelerators?

**Comment by slayoo** [comment]
> I think this will still give 0 at the threshold, instead of ~1.02. Is np.heaviside friendly with the CPU and GPU accelerators?

Thanks, @kaitlyn-loftus !
Hopefully fixed in https://github.com/open-atmos/PySDM/pull/1282/commits/f886fec4463b38d0202c75d8087552e40345fe79

We don't have yet any tests covering GPU for this, so let's address GPU compatibility when we will get there...
Added an assert for the value (which seems to be around 1.2)

**Comment by slayoo** [comment]
@kaitlyn-loftus just a quick update: here's a fresh PR introducing a refactor of the CPU condensation logic which is meant to make the introduction of the ventilation factor there much simpler - https://github.com/open-atmos/PySDM/pull/1291

**Comment by slayoo** [comment]
@kaitlyn-loftus, the https://github.com/open-atmos/PySDM/pull/1282/commits/a40ca41377ecb8e57f68d83cf81e605071511147 commit above contains draft of code for actually using the ventilation coeffs in condensation integrator. This includes a basic test depicting that evaporation of a single droplet in subsaturated env proceeds faster if ventilation if taken into account: https://github.com/open-atmos/PySDM/blob/a40ca41377ecb8e57f68d83cf81e605071511147/tests/unit_tests/dynamics/condensation/test_ventilation.py

Stay tuned for updated GPU code.

**Comment by slayoo** [comment]
@kaitlyn-loftus, CI green! :) 
Please have a look, happy to merge soon and start working on 1D and 2D examples featuring ventilation!
(also, this will be super important for the isotope fractionation developments)

**Comment by kaitlyn-loftus** [comment]
great news!

**Comment by slayoo** [comment]
OK, I'm merging then, and will follow right away with a new release.
Thank you @kaitlyn-loftus!!!

**Review by slayoo — APPROVED** [review]

**Pull request merged**
