### PR TITLE
Implement piecewise-linear rhod profile in condensation methods

### LINKED ISSUE #746: consider piecewise-linear instead of piecewise constant pressure profile in parcel env
CC @claresinger

### LINKED ISSUE #765: FEATURE: Parcel model results depend strongly on dz
We changed the parcel settings to run in `dz` not `dt` (for ease when running with many different `w`). When we did this, we noticed unexpected behavior, where the result of the equilibrium supersaturation reached for the parcel **strongly** depends on the `dz` used even when it is very small (1 m) where we don't think the piecewise constant pressure approximation should lead to any errors.

Minimal example to produce bug on this branch: https://github.com/claresinger/PySDM-examples/tree/ss_eq_error

fig 2 from Lowe example with dz=0.1 m
fig2ab_dz=0 1
fig 2 from Lowe example with dz=1 m
fig2ab_dz=1

### PR DESCRIPTION
**Pull request by mikhailmints**
Closes #746, closes #765.
This implements a piecewise-linear `rhod` profile in the condensation methods instead of using `rhod_mean`. This change makes the condensation solver much less dependent on the timestep in the parcel environment, particularly for parcels with low velocities. For example, before the change, a particular run of the parcel model resulted in the following:
image
There was a very significant difference between the predicted supersaturation for different timestep values, which caused the solver to significantly overestimate the peak supersaturation and activation fraction unless the timestep was set to a very low value.
After the change, the results for different timesteps become nearly identical:
image
TODO: implement the same changes in the ThrustRTC backend.

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you, @mikhailmints !

**Comment by slayoo** [comment]
Also, the plot you included seems a ready-to-use base for a new unit test! Asserting that the two lines match.
In many unit tests, we include a `plot=False` argument, which if turned to `True`, makes the test produce a plot (just before an assert) - so the plot can be included as well, just adding at the end:
```
        if plot:
            pyplot.show()
        else:
            pyplot.clf()
```

**Comment by claresinger** [comment]
Thank you @mikhailmints - looking great! Can you check for convergence with this new linear rhod profile with dz steps rather than dt steps? (Using dz rather than dt will remove the w dependence.) Maybe ranging from dz=0.01 to dz=10m? That would be helpful to know for the examples. You could add this as a plot/convergence test as a unit test, as Sylwester suggested above.

**Comment by trontrytel** [comment]
Looks like `macos-12, 3.7, smoke_tests/parcel` and `macos-12, 3.10, smoke_tests/parcel` are timing out. Not sure what to do about them - could we split that chunk of tests into two to deal with the timing?

I'm bumping this PR, because I think it's a really beneficial update to the default behavior ;)

**Comment by slayoo** [comment]
@trontrytel @mikhailmints @claresinger 

Concerning the timeouts on macOS (which occur within SciPy code, not the PySDM solver), I'd say let's just increase the timeout.
However, I vote for waiting with merging till we have a test added that checks what's visible in the above plots - to make sure that the behaviour is asserted on CI, and that it will be checked for in future developments. @mikhailmints could you give a try at adding the new smoke test? 

We have also the TODO of matching the changes in the ThrustRTC backend, but if well labelled and marked with a new issue, we can defer it for later.

Thanks!

**Comment by slayoo** [comment]
The README parcel example is also a good test case here. If we run it for double the ascent altitude, there is some noise present, which disappears with the changes in this PR. Aiming at committing a README-based test case here soon.

**Pull request merged**
