### PR TITLE
refactor saturation vapour pressure formulae to avoid using temperatures in Celsius

### PR DESCRIPTION
**Pull request by Aphus**
**#1065 refactor saturation vapour pressure formulae to avoid using temperatures in Celsius**

Hello :)

This is my first contribution, so please help me learn and point out any mistakes I might have committed. :smile: 

My approach was to keep things simple and readable. The formulas are unchanged, with a single line converting the input temperature (now in Kelvin) into Celsius.
`T = T - const.T0`

Wherever the svp functions are mentioned, I have removed the adjusting ` - const.T0` factor, and if appropriate, removed the import of constants as `const` from the header of the files.

Files that might require more attention:
> tests/unit_tests/physics/test_saturation_vapour_pressure.py

This one is built around temperature in Celsius and has a plot and a few other elements. It could be rewritten, but I felt like that goes beyond the scope of the issue and is possibly something that you would not want.

> tests/unit_tests/physics/test_formulae.py

```
sut = formulae.saturation_vapour_pressure.pvs_Celsius
T = 300 * si.kelvins

# Act
pvs = sut(T)
```

Temperature here is a bit higher, just wanted to draw attention to this in case passing T=300C was not the intention, since formulas aren't very accurate at those magnitudes.

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you and welcome!
I've just approved the CI run (by default it is not started automatically for new contributors) - let's wait for the CI reports

**Comment by Aphus** [comment]
The error seemed to stem from me having deleted the argument `T0 = T0_C + ...` completely rather than fixing it to simply be T0.

```
env = Parcel(
    # given in the paper
    p0=p0,
>   T0=T0_C + const.T0,
    initial_water_vapour_mixing_ratio=initial_water_vapour_mixing_ratio,
    # arbitrary choices
```

This is now patched, and I will modify the pull request as soon as I figure out how to do that.

**Comment by slayoo** [comment]
The problem with the GPU backend stems from the requirement for all formulae to be one-liners to be compatible with the GPU backend, so the Kelvin-to-Clesius conversion needs to be done in-place there

**Comment by Aphus** [comment]
@slayoo Heya :) Latest changes should make the formulae compatible with the GPU backend.

**Comment by slayoo** [comment]
Thank you!

**Comment by slayoo** [comment]
The CI logs show that there is still some code assuming Celsius scale (with negative temperatures):
```
    def test_saturation_vapour_pressure(plot=False):
        # Arrange
        choices = _choices(saturation_vapour_pressure)
        formulae = {k: Formulae(saturation_vapour_pressure=k) for k in choices}
        temperature = np.linspace(-0.2, 0.4)
    
        # Plot
        pyplot.axhline(const.p_tri, label="triple point", color="red")
        pyplot.axvline(const.T_tri - const.T0, color="red")
        for key, val in formulae.items():
            for name, func in inspect.getmembers(val.saturation_vapour_pressure):
                if name[:2] not in ("__", "a_"):
                    if not (
                        key in ("AugustRocheMagnus", "Wexler1976", "Bolton1980")
                        and name == "pvs_ice"
                    ):
                        pyplot.plot(
>                           temperature, func(temperature), label=f"{key}::{name}"
                        )

tests/unit_tests/physics/test_saturation_vapour_pressure.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

T = array([-0.2       , -0.1877551 , -0.1755102 , -0.16326531, -0.15102041,
       -0.13877551, -0.12653061, -0.11428571, ...204082,  0.31428571,  0.32653061,  0.33877551,
        0.35102041,  0.36326531,  0.3755102 ,  0.3877551 ,  0.4       ])

>   ???
E   RuntimeWarning: invalid value encountered in log
```

**Comment by Aphus** [comment]
We will get there in the end, I promise :smile:

**Review by slayoo — APPROVED** [review]

**Pull request merged**
