### PR TITLE
add Bolin 1958 entry to examples gallery, fix markdown syntax in notebook 

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Review by AgnieszkaZaba — APPROVED** [review]
thank you for this fix!

**Comment by AgnieszkaZaba** [comment]
@slayoo I don't know why there is a problem with `jensen_and_nugent_2017` files. Same is in other runs

**Comment by slayoo** [comment]
seems to be yet another Apple Silicon issue (we're "simply" getting negative arguments for `sqrt()` there, but that's only on Apple Silicon) - to be investigated...

**Comment by AgnieszkaZaba** [comment]
> seems to be yet another Apple Silicon issue (we're "simply" getting negative arguments for `sqrt()` there, but that's only on Apple Silicon) - to be investigated...

Is there an issue for this?

**Comment by slayoo** [comment]
for the record, here's the error log:
```
examples/PySDM_examples/Jensen_and_Nugent_2017/simulation.py:118: in run
    output_products = super()._run(
examples/PySDM_examples/utils/basic_simulation.py:20: in _run
    self._save(output)
examples/PySDM_examples/Jensen_and_Nugent_2017/simulation.py:128: in _save
    super()._save(output)
examples/PySDM_examples/utils/basic_simulation.py:10: in _save
    value = v.get()
PySDM/products/impl/product.py:99: in get
    result = self._impl(**kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <PySDM.products.size_spectral.size_standard_deviation._SizeStandardDeviation object at 0x33aa6f3e0>
kwargs = {}, tmp = array([-6.89228949e-13])

    def _impl(self, **kwargs):
        ActivationFilteredProduct.impl(self, attr=self.attr, rank=1)
        tmp = np.empty_like(self.buffer)
        tmp[:] = -self.buffer**2
        ActivationFilteredProduct.impl(self, attr=self.attr, rank=2)
        tmp[:] += self.buffer
>       tmp[:] = np.sqrt(tmp)
E       RuntimeWarning: invalid value encountered in sqrt

PySDM/products/size_spectral/size_standard_deviation.py:42: RuntimeWarning
```

(it is clearly unrelated to this PR, so rerunning will fix it in all likelihood - which makes it even trickier to actually track the cause...)

**Comment by AgnieszkaZaba** [comment]
I'll try to recreate it locally.

**Pull request merged**
