### PR TITLE
strip backend instances of setattr, more uses of cached_property for backend methods

### PR DESCRIPTION
**Pull request by piotrbartman**
`formulae` or `Storage` should never be overridden

### CODE REVIEW

**Comment by slayoo** [comment]
@piotrbartman, hopefully this PR finally achieves the intended "strict" behavior - `formulae` should not be alterable anymore neither in the backend, nor in particulator instances. Please have a look.

**Comment by slayoo** [comment]
@abulenok, one more piece of rationale behind the non-pythonic removal of `__setattr__` is that as a result the following typo-call causes an error (while without it, it passes silently producing no error and no effect):
```python
backend.formulea = Formulae(constants={...})
```
(note the typo in property name)

**Comment by abulenok** [comment]
> @abulenok, one more piece of rationale behind the non-pythonic removal of `__setattr__` is that as a result the following typo-call causes an error (while without it, it passes silently producing no error and no effect):
> 
> ```python
> backend.formulea = Formulae(constants={...})
> ```
> 
> (note the typo in property name)

@slayoo yeah, but this is true for any object in Python

**Comment by slayoo** [comment]
> > @abulenok, one more piece of rationale behind the non-pythonic removal of `__setattr__` is that as a result the following typo-call causes an error (while without it, it passes silently producing no error and no effect):
> > ```python
> > backend.formulea = Formulae(constants={...})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (note the typo in property name)
> 
> @slayoo yeah, but this is true for any object in Python

Indeed, which is why the [`pystrict`](https://pypi.org/project/pystrict/) package introduces `@strict` decorator (which we extensively use in the examples), and why Pylint would complain in such case

**Comment by slayoo** [comment]
closing this one in favour of a cleaner solution to be proposed and tracked at #1369

**Pull request closed without merging**
