### PR TITLE
Add `FallVelocity` attribute and `RelaxedVelocity` dynamic (and tests)

### PR DESCRIPTION
**Pull request by bradybhalla**
Allows droplets to have a memory of their current velocity and tend towards their terminal velocity over a relaxation timescale. Adds a parameter for existing dynamics to use this attribute instead of terminal velocity. Also includes unit tests for the attribute, dynamic, and initialisation function.

This will allow simulation of super-terminal and sub-terminal droplets as discussed in [this paper](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2008GL037111).

With help from @edejong-caltech.

### CODE REVIEW

**Comment by slayoo** [comment]
Kudos @bradybhalla !!!

The CI checks run `pylint` and `pre-commit` commands, which can be executed locally as described here:
- https://github.com/open-atmos/python-dev-hints/wiki/Pre-commit-FAQ
- https://github.com/open-atmos/python-dev-hints/wiki/Pylint-FAQ

I'll be in travels over the next days, but will do my best to get acquainted, provide comments, and help with merging

**Comment by bradybhalla** [comment]
I think I fixed all the linting errors, but pylint seemed to be having trouble with imports on my computer so there still may be a problem there. I also ran pre-commit and the formatting should be fixed.  Thanks for your help!

**Comment by slayoo** [comment]
pylint and pre-commit checks all green! 

One idea/question: would it make the code a bit simpler to make all the collision and displacement codes always use a `fall velocity` attribute (without any conditional expressions there); while within `mapper.py` we would pick `terminal velocity` class as implementation for the `fall velocity` in case the new dynamic is not present; or the new attribute if it was added to the builder. Similarly as in the case of the choice between `DryVolume` and `DryVolumeDynamic` for handling of "dry volume" attribute in `mapper.py`.

**Comment by slayoo** [comment]
One more thought: both the fall and the terminal velocities are treated here as relative to the air flow, hence actually the droplets are not falling with their fall velocities (sic!) - perhaps we could hint it somehow in the attribute and class names? 

`RelativeFallVelocity`? or `AirFlowRelativeFallVelocity`?

**Comment by bradybhalla** [comment]
> would it make the code a bit simpler to make all the collision and displacement codes always use a fall velocity attribute (without any conditional expressions there); while within mapper.py we would pick TerminalVelocity class as implementation for the fall velocity attribute in case the new dynamic is not present

Yes I think this would simplify the code, because currently the user will have to specify it for every dynamic. I will work on adding this!



> One more thought: both the fall and the terminal velocities are treated here as relative to the air flow, hence actually the droplets are not falling with their fall velocities (sic!) - perhaps we could hint it somehow in the attribute and class names?
> 
> `RelativeFallVelocity`? or `AirFlowRelativeFallVelocity`?

This is also a good idea, I will make the necessary changes.

**Comment by bradybhalla** [comment]
I renamed `FallVelocity` to `RelativeFallVelocity` and changed the mapper to actually use `TerminalVelocity` if there is no `RelaxedVelocity` dynamic added to the builder.

Tomorrow I will add a unit test to ensure the correct attribute is being selected. I also messed something up with the `Displacement` dynamic which I will fix tomorrow.

I am also not quite sure what is the best way to handle the `RelativeFallMomentum` attribute.  It is used only as an intermediary to calculate the fall velocity, but would it be good to create a `TerminalFallMomentum` attribute which is used if no `RelaxedVelocity` dynamic is present?  Currently the fall momentum will never get changed with no dynamic.

**Comment by slayoo** [comment]
Thank you, @bradybhalla!
Concerning the warning, perhaps we can re-use here the `make_dummy_attribute_factory` which seems intended exactly for this purpose, and add the warning-issuing line inside it (as of now, the `DummyAttribute` simply fills data with NaNs on every call)?

Kudos for all the unit tests!

**Comment by slayoo** [comment]
trying if closing and reopening would sort out `README.md` changes from other PR popping up here?

**Review by slayoo — APPROVED** [review]

**Comment by slayoo** [comment]
@bradybhalla I've just committed a few cosmetic changes - please have a look and confirm it that is all OK, and let's merge!
Big thanks for this contribution!

**Comment by bradybhalla** [comment]
It looks great to me! Thank you for all your help getting the code ready to merge!

**Review by slayoo — APPROVED** [review]

**Comment by slayoo** [comment]
Just added one more unit test (checking if a warning is issues by `request_attribute`).
After CI will be green, I'll merge and make a new release.
Thanks!

**Pull request merged**
