### PR TITLE
bump devops tests to include checks for notebook badges

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by AgnieszkaZaba** [comment]
I need someone else to rerun demos with numba.

**Comment by AgnieszkaZaba** [comment]
@slayoo only one notebook should be incorrect: it's [performance comparison](https://github.com/slayoo/PySDM/blob/issue_1449/examples/PySDM_examples/Bulenok_2023_MasterThesis/performance_comparison_Srivastava_Setup.ipynb) 
Inside is a comparison between using numba and ThrustRC. And running it without numba is not only very long but also meaningless.

Don't know why the others are wrong, I change them many times. Will try once again.

**Comment by slayoo** [comment]
> @slayoo only one notebook should be incorrect: it's [performance comparison](https://github.com/slayoo/PySDM/blob/issue_1449/examples/PySDM_examples/Bulenok_2023_MasterThesis/performance_comparison_Srivastava_Setup.ipynb) Inside is a comparison between using numba and ThrustRC. And running it without numba is not only very long but also meaningless.
> 
> Don't know why the others are wrong, I change them many times. Will try once again.

@AgnieszkaZaba, Numba is enabled when running the notebooks on CI. There are no GPUs available on CI, but we have `FakeThrustRTC` mock class specifically developed to emulate ThrustRTC using Numba. I'd say running these is not meaningless as it ensures that the notebook code is compatible with the evolving PySDM API, so if one runs it on a local machine, it's likely that it will actually work.

**Comment by AgnieszkaZaba** [comment]
> > @slayoo only one notebook should be incorrect: it's [performance comparison](https://github.com/slayoo/PySDM/blob/issue_1449/examples/PySDM_examples/Bulenok_2023_MasterThesis/performance_comparison_Srivastava_Setup.ipynb) Inside is a comparison between using numba and ThrustRC. And running it without numba is not only very long but also meaningless.
> > Don't know why the others are wrong, I change them many times. Will try once again.
> 
> @AgnieszkaZaba, Numba is enabled when running the notebooks on CI. There are no GPUs available on CI, but we have `FakeThrustRTC` mock class specifically developed to emulate ThrustRTC using Numba. I'd say running these is not meaningless as it ensures that the notebook code is compatible with the evolving PySDM API, so if one runs it on a local machine, it's likely that it will actually work.

Ok, you're right. I'm still waiting for Jupyter to finish running :)

**Comment by slayoo** [comment]
> > > @slayoo only one notebook should be incorrect: it's [performance comparison](https://github.com/slayoo/PySDM/blob/issue_1449/examples/PySDM_examples/Bulenok_2023_MasterThesis/performance_comparison_Srivastava_Setup.ipynb) Inside is a comparison between using numba and ThrustRC. And running it without numba is not only very long but also meaningless.
> > > Don't know why the others are wrong, I change them many times. Will try once again.
> > 
> > 
> > @AgnieszkaZaba, Numba is enabled when running the notebooks on CI. There are no GPUs available on CI, but we have `FakeThrustRTC` mock class specifically developed to emulate ThrustRTC using Numba. I'd say running these is not meaningless as it ensures that the notebook code is compatible with the evolving PySDM API, so if one runs it on a local machine, it's likely that it will actually work.
> 
> Ok, you're right. I'm still waiting for Jupyter to finish running :)

Ah, I didn't realise you are referring to running the GPU tests locally on a machine without GPU to generate notebook output. That is indeed meaningless. Perhaps, we could convert this notebook into a .py script so that it would be stored in the repo, but without output?

**Comment by AgnieszkaZaba** [comment]
> > > > @slayoo only one notebook should be incorrect: it's [performance comparison](https://github.com/slayoo/PySDM/blob/issue_1449/examples/PySDM_examples/Bulenok_2023_MasterThesis/performance_comparison_Srivastava_Setup.ipynb) Inside is a comparison between using numba and ThrustRC. And running it without numba is not only very long but also meaningless.
> > > > Don't know why the others are wrong, I change them many times. Will try once again.
> > > 
> > > 
> > > @AgnieszkaZaba, Numba is enabled when running the notebooks on CI. There are no GPUs available on CI, but we have `FakeThrustRTC` mock class specifically developed to emulate ThrustRTC using Numba. I'd say running these is not meaningless as it ensures that the notebook code is compatible with the evolving PySDM API, so if one runs it on a local machine, it's likely that it will actually work.
> > 
> > 
> > Ok, you're right. I'm still waiting for Jupyter to finish running :)
> 
> Ah, I didn't realise you are referring to running the GPU tests locally on a machine without GPU to generate notebook output. That is indeed meaningless. Perhaps, we could convert this notebook into a .py script so that it would be stored in the repo, but without output?

Hmm I feel like this output is important and should be stored somewhere. Not necessarily in notebook. I'm trying to run it on Colab. Keep disconnecting me but program is still running and giving results, so maybe will be ok.

**Comment by slayoo** [comment]
> > > > > @slayoo only one notebook should be incorrect: it's [performance comparison](https://github.com/slayoo/PySDM/blob/issue_1449/examples/PySDM_examples/Bulenok_2023_MasterThesis/performance_comparison_Srivastava_Setup.ipynb) Inside is a comparison between using numba and ThrustRC. And running it without numba is not only very long but also meaningless.
> > > > > Don't know why the others are wrong, I change them many times. Will try once again.
> > > > 
> > > > 
> > > > @AgnieszkaZaba, Numba is enabled when running the notebooks on CI. There are no GPUs available on CI, but we have `FakeThrustRTC` mock class specifically developed to emulate ThrustRTC using Numba. I'd say running these is not meaningless as it ensures that the notebook code is compatible with the evolving PySDM API, so if one runs it on a local machine, it's likely that it will actually work.
> > > 
> > > 
> > > Ok, you're right. I'm still waiting for Jupyter to finish running :)
> > 
> > 
> > Ah, I didn't realise you are referring to running the GPU tests locally on a machine without GPU to generate notebook output. That is indeed meaningless. Perhaps, we could convert this notebook into a .py script so that it would be stored in the repo, but without output?
> 
> Hmm I feel like this output is important and should be stored somewhere. Not necessarily in notebook. I'm trying to run it on Colab. Keep disconnecting me but program is still running and giving results, so maybe will be ok.

The output is also persistently stored in the UJ AP repo (pages 29-30): https://www.ap.uj.edu.pl/diplomas/attachments/file/download/168064/

**Comment by AgnieszkaZaba** [comment]
> > > > > > @slayoo only one notebook should be incorrect: it's [performance comparison](https://github.com/slayoo/PySDM/blob/issue_1449/examples/PySDM_examples/Bulenok_2023_MasterThesis/performance_comparison_Srivastava_Setup.ipynb) Inside is a comparison between using numba and ThrustRC. And running it without numba is not only very long but also meaningless.
> > > > > > Don't know why the others are wrong, I change them many times. Will try once again.
> > > > > 
> > > > > 
> > > > > @AgnieszkaZaba, Numba is enabled when running the notebooks on CI. There are no GPUs available on CI, but we have `FakeThrustRTC` mock class specifically developed to emulate ThrustRTC using Numba. I'd say running these is not meaningless as it ensures that the notebook code is compatible with the evolving PySDM API, so if one runs it on a local machine, it's likely that it will actually work.
> > > > 
> > > > 
> > > > Ok, you're right. I'm still waiting for Jupyter to finish running :)
> > > 
> > > 
> > > Ah, I didn't realise you are referring to running the GPU tests locally on a machine without GPU to generate notebook output. That is indeed meaningless. Perhaps, we could convert this notebook into a .py script so that it would be stored in the repo, but without output?
> > 
> > 
> > Hmm I feel like this output is important and should be stored somewhere. Not necessarily in notebook. I'm trying to run it on Colab. Keep disconnecting me but program is still running and giving results, so maybe will be ok.
> 
> The output is also persistently stored in the UJ AP repo (pages 29-30): https://www.ap.uj.edu.pl/diplomas/attachments/file/download/168064/

That is great! I will add this link to the notebook. 
And maybe .py will be better. Not sure. Because even with GPU run time is long. So maybe shorten in notebook? Or change to .py as you suggested..

**Comment by slayoo** [comment]
> > > > > > > @slayoo only one notebook should be incorrect: it's [performance comparison](https://github.com/slayoo/PySDM/blob/issue_1449/examples/PySDM_examples/Bulenok_2023_MasterThesis/performance_comparison_Srivastava_Setup.ipynb) Inside is a comparison between using numba and ThrustRC. And running it without numba is not only very long but also meaningless.
> > > > > > > Don't know why the others are wrong, I change them many times. Will try once again.
> > > > > > 
> > > > > > 
> > > > > > @AgnieszkaZaba, Numba is enabled when running the notebooks on CI. There are no GPUs available on CI, but we have `FakeThrustRTC` mock class specifically developed to emulate ThrustRTC using Numba. I'd say running these is not meaningless as it ensures that the notebook code is compatible with the evolving PySDM API, so if one runs it on a local machine, it's likely that it will actually work.
> > > > > 
> > > > > 
> > > > > Ok, you're right. I'm still waiting for Jupyter to finish running :)
> > > > 
> > > > 
> > > > Ah, I didn't realise you are referring to running the GPU tests locally on a machine without GPU to generate notebook output. That is indeed meaningless. Perhaps, we could convert this notebook into a .py script so that it would be stored in the repo, but without output?
> > > 
> > > 
> > > Hmm I feel like this output is important and should be stored somewhere. Not necessarily in notebook. I'm trying to run it on Colab. Keep disconnecting me but program is still running and giving results, so maybe will be ok.
> > 
> > 
> > The output is also persistently stored in the UJ AP repo (pages 29-30): https://www.ap.uj.edu.pl/diplomas/attachments/file/download/168064/
> 
> That is great! I will add this link to the notebook. And maybe .py will be better. Not sure. Because even with GPU run time is long. So maybe shorten in notebook? Or change to .py as you suggested..

Thank you!
GPU times should be shorter than CPU=Numba (for large-enough domain, as depicted in the thesis plots).

**Comment by AgnieszkaZaba** [comment]
@slayoo thanks for rebasing, I didn't succeed with that.

Right now I'm trying to run notebooks but after 5 hours still do not have results

**Comment by slayoo** [comment]
> @slayoo thanks for rebasing, I didn't succeed with that.

This was a merge. For PR branches, merges are usually straightforward, and thus much simpler than rebasing. Rebasing works best for the always-clean `main` branch.
 
> Right now I'm trying to run notebooks but after 5 hours still do not have results

Which notebooks take so long?

**Comment by AgnieszkaZaba** [comment]
> > @slayoo thanks for rebasing, I didn't succeed with that.
> 
> This was a merge. For PR branches, merges are usually straightforward, and thus much simpler than rebasing. Rebasing works best for the always-clean `main` branch.
> 

aa ok, still dont fully understand, but I will get there.

> > Right now I'm trying to run notebooks but after 5 hours still do not have results
> 
> Which notebooks take so long?

From deJong_Mackay_et_al_2023 fig9 and figs_3_4_5

**Comment by slayoo** [comment]
> > > @slayoo thanks for rebasing, I didn't succeed with that.
> > 
> > 
> > This was a merge. For PR branches, merges are usually straightforward, and thus much simpler than rebasing. Rebasing works best for the always-clean `main` branch.
> 
> aa ok, still dont fully understand, but I will get there.

https://learngitbranching.js.org/

**Comment by AgnieszkaZaba** [comment]
> > > @slayoo thanks for rebasing, I didn't succeed with that.
> > 
> > 
> > This was a merge. For PR branches, merges are usually straightforward, and thus much simpler than rebasing. Rebasing works best for the always-clean `main` branch.
> 
> aa ok, still dont fully understand, but I will get there.
> 
> > > Right now I'm trying to run notebooks but after 5 hours still do not have results
> > 
> > 
> > Which notebooks take so long?
> 
> From deJong_Mackay_et_al_2023 fig9 and figs_3_4_5

For both notebook it was around 11 hours 😮

**Pull request merged**
