### PR TITLE
bump devops_tests to include checks for badge presence and Colab header cell

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by slayoo** [comment]
OK, this PR gets much higher priority now - without the new checks we cannot rely on badge presence in the first header cell, what results in fishy docs contents, e.g.:
image

**Comment by AgnieszkaZaba** [comment]
I think we should change devops_tests, because in probably every notebook we wrote View on Github instead of preview. So it will be easier to change test.

**Comment by AgnieszkaZaba** [comment]
@slayoo, I don't know how to resolve this. I think it is due to different changes in the same files on your fork and PySDM repository.

**Comment by slayoo** [comment]
> @slayoo, I don't know how to resolve this. I think it is due to different changes in the same files on your fork and PySDM repository.

@AgnieszkaZaba, the conflicting file was renamed on the `main` branch of `open-atmos` in a recent PR, which was causing the conflict. Resolved.

**Comment by slayoo** [comment]
Thank you @AgnieszkaZaba!

**Pull request merged**
