### PR TITLE
S&H example surface precip product compatibility

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by slayoo** [comment]
@crocicc, let us know if this would help with the S&H surface precip product issue?

**Comment by crocicc** [comment]
> @crocicc, let us know if this would help with the S&H surface precip product issue?

@slayoo I am running a file that is not `test_few_steps.py`, so I didn't have to apply the changes that you suggested in that file. However, I changed the `simulation.py` code and it makes my code run without problems. Tomorrow I'll make a few more checks and confirm you if everything works correctly. 
Thanks a lot!

**Comment by slayoo** [comment]
> > @crocicc, let us know if this would help with the S&H surface precip product issue?
> 
> @slayoo I am running a file that is not `test_few_steps.py`, so I didn't have to apply the changes that you suggested in that file. However, I changed the `simulation.py` code and it makes my code run without problems. Tomorrow I'll make a few more checks and confirm you if everything works correctly. Thanks a lot!

Thanks, looks promising then. The test file is actually not meant for users, it is automatically executed in the GitHub cloud to assert that the newly added/modified code works as expected (and will continue so upon further developments)

**Comment by crocicc** [comment]
> > > @crocicc, let us know if this would help with the S&H surface precip product issue?
> > 
> > 
> > @slayoo I am running a file that is not `test_few_steps.py`, so I didn't have to apply the changes that you suggested in that file. However, I changed the `simulation.py` code and it makes my code run without problems. Tomorrow I'll make a few more checks and confirm you if everything works correctly. Thanks a lot!
> 
> Thanks, looks promising then. The test file is actually not meant for users, it is automatically executed in the GitHub cloud to assert that the newly added/modified code works as expected (and will continue so upon further developments)

I confirm you that with these changes the product works for my case! Thank you so much for your help!

**Pull request merged**
