### PR TITLE
removing obsolete code (TODO: add test depicting how to change terminal velocity formulation)

### PR DESCRIPTION
**Pull request by slayoo**
thanks Brady Bhalla for pointing this out!

### CODE REVIEW

**Comment by slayoo** [comment]
let's aim at adding a test depicting how to switch between different terminal velocity formulations, and checking that the logic in `PySDM/attributes/physics/terminal_velocity.py` correctly picks the selected formulation.

Currently, we have `test_terminal_velocity.py` (https://github.com/open-atmos/PySDM/blob/main/tests/unit_tests/attributes/test_terminal_velocity.py) that checks how two existing formulations work, but it does not check if this works with attributes

**Comment by slayoo** [comment]
@bradybhalla, what we are missing here is a test or example depicting how users would switch to different terminal velocity approximations. Help welcome, thanks

**Comment by bradybhalla** [comment]
@slayoo sorry I haven't gotten a chance to look at this yet. Should we leave it up to the user to manually change the `approximation` after the terminal velocity attribute is created as in the removed code? Another possibility could be to have the correct approximation selected when the attribute is created based on a parameter passed to `Formulae`.

**Comment by slayoo** [comment]
@abulenok, @bradybhalla shall we merge this one upon merging #1168?

**Review by abulenok — APPROVED** [review]

**Pull request merged**
