### PR TITLE
Lowe et al. 2019 Fig S2 (+smoke tests); new optical formulae and products (optical depth & albedo); LWP product; activation-filtered r_eff product; cleanups

### PR DESCRIPTION
**Pull request by claresinger**
TODO 
- [x] move optical calculations into Products and Formulae (see #1251)
- [x] switch to filtered reff for tau calculation
- [x] switch the CDNC from ActivatedFraction * Na to using the new filtered product

### CODE REVIEW

**Comment by claresinger** [comment]
pylint error is confusing because the "unused imports" are actually used in the notebook...

```
************* Module PySDM_examples.Lowe_et_al_2019.fig_s2
examples/PySDM_examples/Lowe_et_al_2019/fig_s2.ipynb:cell_2:4:0: W0611: Unused show_plot imported from open_atmos_jupyter_utils (unused-import)
examples/PySDM_examples/Lowe_et_al_2019/fig_s2.ipynb:cell_2:8:0: W0611: Unused in_unit imported from PySDM.physics (unused-import)
examples/PySDM_examples/Lowe_et_al_2019/fig_s2.ipynb:cell_2:14:0: W0611: Unused pyplot imported from matplotlib (unused-import)

-----------------------------------
Your code has been rated at 9.99/10
```

**Comment by slayoo** [comment]
@claresinger for the massive number of precommit changes (caused by a new release of black just 2 days ago: https://pypi.org/project/black/24.1.0/), let's have a separate PR: #1257

**Comment by slayoo** [comment]
OK, we're back at "Files changed: 16" :)

**Comment by claresinger** [comment]
@slayoo I'm going to need some help with the logic for calculating the integral products... an attempt is in `cloud_water_path.py` :)

**Comment by claresinger** [comment]
Currently I have in the fig_s2.ipynb notebook these lines that use the formulae to calculate optical depth and albedo.
```
    # todo move these calculations to Products
    optical_products[key]["tau"] = FORMULAE.optical_depth.tau(optical_products[key]["lwp"], optical_products[key]["reff"])
    optical_products[key]["albedo"] = FORMULAE.cloud_albedo.albedo(optical_products[key]["tau"])
```

I would like this to be done as a Product instead so in the notebook it can just say `optical_products[key]["tau"] = out_item['tau'][cloud_top_index]`. Just like is done for `lwp` etc.

@slayoo - Is there a simple way to use one product to calculate another product? How can I use the formulae inside of the CloudOpticalDepth product given the result from CloudWaterPath() and ActivatedEffectiveRadius() products?
```
from PySDM.products.impl.product import Product
from PySDM.products.size_spectral.effective_radius_activated import (
    ActivatedEffectiveRadius,
)
from PySDM.products.displacement.cloud_water_path import CloudWaterPath

class CloudOpticalDepth(Product):
    def __init__(self, *, unit="dimensionless", name=None):
        super().__init__(name=name, unit=unit)

    def register(self, builder):
        pass

    def _impl(self, **kwargs):
        return self.formulae.optical_depth.tau(
            CloudWaterPath(),
            ActivatedEffectiveRadius(count_unactivated=False, count_activated=True),
        )
```

**Comment by slayoo** [comment]
@claresinger there is no logic implemented yet to make one product depend on another one. In fact, any product calculations are currently triggered by the user by invoking `get()` on a product, so this pattern would need to be changed first to allow for any automation of dependencies? But in fact, already in the Lowe examples, we have one product that depends on another one, namely the "Activated Fraction". There, it is handled manually within `simulation.py`. So, here's a try at doing it analogously: https://github.com/open-atmos/PySDM/pull/1256/commits/2732eac29f10be62c22c83db4283fe05f69ce7f8

**Comment by slayoo** [comment]
Also, I wonder if the LWP difference wrt the paper isn't related with our parcel volume integration logic?
Anyhow, it would be worth to add some unit tests validating the integration.
In `parcel.py` we have this `rhod_mean` magic which should likely be somehow referenced - I'd say that the integration should be part of the `parcel.py`... and then for other environments, the column integration would also be within the environment file to provide alternative formulations.

**Review by slayoo — APPROVED** [review]

**Comment by claresinger** [comment]
Closes #1251

**Pull request merged**
