### PR TITLE
introducing PySDM tutorials with first two based on collision and condensation classroom notebooks

### PR DESCRIPTION
**Pull request by claresinger**
best to get these merged into the main repo so they don't get left behind again!

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you, @claresinger!

Some initial thoughts:
- let's perhaps create a new subdirectory "tutorials" next to "examples" (and perhaps rename "examples" to "examples-literature" or alike) to separate notebooks that are intended to reproduce figures from literature (and thus also serve as validation of PySDM) from notebooks that are more of standalone introductory material 
- let's perhaps add some smoke tests to the new tutorial-examples, if feasible, to ensure that these are maintainable (to get a red flag in case some new fieature of PySDM would make the notebooks produce different plots)
- let's replace raster graphics (png) with vector ones here (svg)
- let's replace nbviewer badges with links to github badges - GitHub ipynb support has improved a lot, and now displays the notebooks and graphics much more robustly than nbviewer, which in fact in most cases chokes on vector graphics

@AgnieszkaMakulska, let me ask you for further feedback.

Thanks!

**Comment by AgnieszkaMakulska** [comment]
Hello! I have encountered a problem with running the new notebooks in Google Colab. I think that links to Colab may be wrong, because the notebooks in Colab have the following line:

`!pip --quiet install atmos-cloud-sim-uj-utils`

which results in an error. The files in the repository have instead the line

`!pip --quiet install "open-atmos-jupyter-utils" `.

When I change the file in Colab to match the file in the repository , in the `class_condensation_playground.ipynb` notebook I get the following error:

*No module named 'PySDM_examples.Pyrcel.class_condensation_settings’*

Maybe it is bacause modules `.class_condensation_settings` and `.class_condensation_simulation` are not imported in the `__innit__.py` file in the Pyrcel folder? There is a similar problem with importing modules in the `class_collisions_playground.ipynb` notebook.

**Comment by slayoo** [comment]
Thanks @AgnieszkaMakulska! 

> !pip --quiet install atmos-cloud-sim-uj-utils
>
> which results in an error. The files in the repository have instead the line
>
> !pip --quiet install "open-atmos-jupyter-utils" .

The latter is presently correct (back a year ago, this package was renamed).
(just elevated your persmissions in the PySDM repo, and you should be able to push to Clare's branch)

Concerning testing on Colab, unfortunately we still do not have a robust workflow for PRs because `pip install` calls within the notebooks are installing files from the released versions of PySDM, not from the PR code.

**Comment by AgnieszkaMakulska** [comment]
Following the suggestions of @slayoo , I moved the files to a subdirectory "tutorials" and I changed the badges and links to Colab. The notebooks work well on my computer.

**Comment by slayoo** [comment]
@abulenok, could you please help us in getting the tutorial notebooks executed as a new "suite" on CI?

**Comment by claresinger** [comment]
Any advice on the pylint notebook errors much appreciated! The notebooks run fine locally. I'm getting two errors: "import-error" and "redefined-outer-name". 

1) When I try to fix the import errors using the full paths e.g. "condensation settings" --> "tutorials.condensation.condensation_settings" I get import errors locally. 

2) Is this coming from having "n_SD" as a function argument and then defined in the next cell? This doesn't seem like a problem, why is it a pylint error? Is it a warning we want to disable?

**Comment by slayoo** [comment]
@claresinger, thank you for moving this forward!

Regarding imports, the key problem here is that there is no way Colab can access these files as these are neigher part of PySDM not PySDM-examples. Colab installs PySDM-examples (and PySDM as dependency) and downloads the single .ipynb file from github, but nothing more. Likely, the easiest way out would be to include the common files within the PySDM-examples package.

See: https://colab.research.google.com/github/claresinger/PySDM/blob/classroom_examples/tutorials/condensation/condensation_playground.ipynb
```
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-3-bcf11507cf51>](https://localhost:8080/#) in <cell line: 17>()
     15 
     16 # import tools for running and plotting this example
---> 17 from condensation_settings import Settings
     18 from condensation_simulation import Simulation
     19 from profile_plotter import ProfilePlotter

ModuleNotFoundError: No module named 'condensation_settings'
```

Regarding function argument names that shadow variables from outer scope, I'd say that this is a very valid and useful suggestion by pylint! I understand that it is considered error prone and misleading for the readers. One way out would be to rename the function arguments. 

BTW, the badge URLs here still point to your fork.

**Comment by claresinger** [comment]
@abulenok Hi Oleksii! Happy new year! Could you take a look at why the tutorial tests are failing? What does it mean there is no module named git? Thank you for your help!
```
==================================== ERRORS ====================================
_________ ERROR collecting tests/tutorials_tests/test_run_notebooks.py _________
ImportError while importing test module '/Users/runner/work/PySDM/PySDM/tests/tutorials_tests/test_run_notebooks.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/tutorials_tests/test_run_notebooks.py:2: in <module>
    from ..devops_tests.test_notebooks import test_run_notebooks as _impl
tests/devops_tests/test_notebooks.py:18: in <module>
    from git.cmd import Git
E   ModuleNotFoundError: No module named 'git'
```

**Comment by slayoo** [comment]
@claresinger @abulenok 

using devops_tests requires installation of `devops_tests/requirements.txt`, like here:
https://github.com/open-atmos/PySDM/blob/72a789278679aed84ee1d09fc55ba2f1495b38cf/.github/workflows/tests%2Bartifacts%2Bpypi.yml#L100

Also, since we do not intend to use the tutorials forlder for anything but .ipynb files (since .py files placed there are not part of any pip-installable package, and hence are not usable on Colab), we can/should remove:
- `tutorials/__init__.py`
- `tests/tutorials_tests/test_run_tutorials.py`
- the `tutorial_filename` definition from `conftest.py`

**Comment by slayoo** [comment]
indeed, commenting out the call to `widgets.interactive_output` makes the timeout go away... perhaps let's do something like:
```python
if 'CI' not in os.environ:
    widgets.display(sliders, boxes, progbar, widgets.interactive_output(...))
```

BTW, the `from IPython.display import display` line is not needed as you can use `widgets.display` here

**Comment by slayoo** [comment]
@claresinger two final points before we merge:
- suggest adding a new section to the README file with a list of tutorials with links allowing to execute them in Colab/mybinder
- the badges in the notebooks have bogus urls - all point to `class_` prefixed .ipynb files

**Comment by slayoo** [comment]
kudos @claresinger!!!
thank you @AgnieszkaMakulska & @abulenok for help!

**Pull request merged**
